title: Woulve's Blog

defaultContentLanguage: en
defaultContentLanguageInSubdir: true

module:
  imports:
    - path: github.com/imfing/hextra

languages:
  en:
    languageCode: en-US
    languageName: English
    weight: 1
  de:
    languageCode: de-DE
    languageName: Deutsch
    weight: 2

caches:
  images:
    dir: :cacheDir/images
