title: Woulve's Blog

defaultContentLanguage: en

# module:
#   imports:
#     - path: github.com/imfing/hextra
theme: hextra

languages:
  en:
    languageCode: en-US
    languageName: English
    weight: 1
  de:
    languageCode: de-DE
    languageName: Deutsch
    weight: 2

caches:
  images:
    dir: :cacheDir/images
