main:
  - identifier: blog
    name: Blog
    pageRef: /blog
    weight: 1
  # - identifier: about
  #   name: About
  #   pageRef: /about
  #   weight: 2
  - identifier: search
    name: Search
    weight: 3
    params:
      type: search
  - identifier: github
    name: GitHub
    weight: 4
    url: "https://github.com/Woulve/"
    params:
      icon: github
  - identifier: language-switcher
    name: Language Switcher
    params:
      type: language-switch
      label: true
      icon: "translate"