navbar:
  displayTitle: true
  displayLogo: true
  logo:
    path: images/woulve.webp
    width: 50
    height: 20
blog:
  list:
    displayTags: true
footer:
  displayPoweredBy: false
page:
  width: wide